# Generated by Django 5.1.15 on 2026-10-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='question',
            name='shift',
            field=models.CharField(blank=True, choices=[('Shift 1', 'Shift 1'), ('Shift 2', 'Shift 2'), ('Shift 3', 'Shift 3')], max_length=10),
        ),
    ]
