# Generated by Django 5.1.15 on 2026-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_alter_subject_options_question_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='shift',
            field=models.CharField(blank=True, choices=[('First', 'First Shift'), ('Second', 'Second Shift')], max_length=10),
        ),
    ]
